# Generated by Django 5.2.8 on 2026-04-17 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='Imagen')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('property_type', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('terreno', 'Terreno'), ('local', 'Local'), ('oficina', 'Oficina')], max_length=20, verbose_name='Tipo')),
                ('operation_type', models.CharField(choices=[('venta', 'Venta'), ('arriendo', 'Arriendo')], max_length=20, verbose_name='Operación')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área (m²)')),
                ('rooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Habitaciones')),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Baños')),
                ('address', models.CharField(max_length=300, verbose_name='Dirección')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='Características adicionales')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada'), ('sold', 'Vendida'), ('rented', 'Arrendada')], default='draft', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='locations.municipality')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-created_at'],
            },
        ),
    ]
