# Generated by Django 5.2.8 on 2026-04-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_add_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Área (m²)'),
        ),
    ]
